use super::*;
use crate::chips::decompose_8::Decompose8Config;
use crate::chips::generic_limb_rotation::LimbRotationConfig;
use ff::PrimeField;
use halo2_proofs::circuit::SimpleFloorPlanner;
use halo2_proofs::plonk::{Circuit, Fixed};
use std::array;

#[derive(Clone)]
pub struct LimbRotationConfigAutogenerated<F: PrimeField> {
    limb_rotation_config: LimbRotationCircuitConfig<F>,
    fixed: Column<Fixed>,
}

#[derive(Clone)]
pub struct LimbRotationCircuitAutogenerated<F: PrimeField, const T: usize> {
    _ph: PhantomData<F>,
    input: Value<F>,
    result: Value<F>,
}

impl<F: PrimeField, const T: usize> LimbRotationCircuitAutogenerated<F, T> {
    pub fn new_for(input: Value<F>, expected_output: Value<F>) -> Self {
        Self {
            _ph: PhantomData,
            input,
            result: expected_output,
        }
    }
}

impl<F: PrimeField, const T: usize> Circuit<F> for LimbRotationCircuitAutogenerated<F, T> {
    type Config = LimbRotationConfigAutogenerated<F>;
    type FloorPlanner = SimpleFloorPlanner;

    fn without_witnesses(&self) -> Self {
        Self {
            _ph: PhantomData,
            input: Value::unknown(),
            result: Value::unknown(),
        }
    }

    fn configure(meta: &mut ConstraintSystem<F>) -> Self::Config {
        let full_number_u64 = meta.advice_column();
        let limbs: [Column<Advice>; 8] = array::from_fn(|_| {
            let column = meta.advice_column();
            meta.enable_equality(column);
            column
        });
        let fixed = meta.fixed_column();
        meta.enable_equality(fixed);
        meta.enable_equality(full_number_u64);

        let decompose_8_config = Decompose8Config::configure(meta, full_number_u64, limbs);
        let limb_rotation_config = LimbRotationConfig::new();

        Self::Config {
            limb_rotation_config: LimbRotationCircuitConfig {
                _ph: PhantomData,
                decompose_8_config,
                limb_rotation_config,
            },
            fixed,
        }
    }

    fn synthesize(
        &self,
        mut config: Self::Config,
        mut layouter: impl Layouter<F>,
    ) -> Result<(), Error> {
        let limbs_to_rotate_to_the_right = match T {
            32 => 4,
            24 => 3,
            16 => 2,
            _ => panic!("Unexpected Rotation"),
        };

        config.limb_rotation_config.decompose_8_config.populate_lookup_table(&mut layouter)?;
        layouter.assign_region(
            || format!("Rotate {} limbs", limbs_to_rotate_to_the_right),
            |mut region| {
                let mut offset = 0;
                let result = config
                    .limb_rotation_config
                    .limb_rotation_config
                    .generate_rotation_rows_from_value(
                        &mut region,
                        &mut offset,
                        &mut config.limb_rotation_config.decompose_8_config,
                        self.input,
                        limbs_to_rotate_to_the_right,
                    )?;

                // Check that the calculation was performed correctly by the limb rotation chip
                let fixed_cell = region.assign_fixed(
                    || "assign expected result",
                    config.fixed,
                    0,
                    || self.result,
                )?;
                region.constrain_equal(result.cell(), fixed_cell.cell())?;
                Ok(())
            },
        )?;

        Ok(())
    }
}
