use super::*;
use crate::chips::decompose_8::Decompose8Config;
use crate::chips::generic_limb_rotation_chip::LimbRotationChip;
use crate::chips::rotate_63_chip::Rotate63Chip;

mod rotation_63_circuit_16bit_limbs;
#[cfg(test)]
mod test_rotation_63_16_bit_limbs;

// -------- Rotation 63 with 8 bit limbs ------------
mod rotation_63_circuit_8bit_limbs;
#[cfg(test)]
mod test_rotation_63_8_bit_limbs;

mod rotation_63_cirtuit_8bit_limbs_autogenerated;
#[cfg(test)]
mod test_rotation_63_8_bit_limbs_autogenerated;

#[derive(Clone)]
pub struct Rotation63Config8bitLimbs<F: PrimeField> {
    _ph: PhantomData<F>,
    rotation_63_chip: Rotate63Chip<F, 8, 9>,
    decompose_8_chip: Decompose8Config<F>,
}

// --------------------------------------------------

#[cfg(test)]
mod limb_rotation_circuit;
mod test_limb_rotation_16_24_32;

mod limb_rotation_circuit_autogenerated;
#[cfg(test)]
mod test_limb_rotation_16_24_32_autogenerated;

#[derive(Clone)]
pub struct LimbRotationConfig<F: PrimeField> {
    _ph: PhantomData<F>,
    decompose_8_chip: Decompose8Config<F>,
    limb_rotation_chip: LimbRotationChip<F>,
}
