use super::*;
use crate::chips::decompose_8_chip::Decompose8Chip;
use crate::chips::xor_chip::XorChip;

mod tests_xor_with_generated_trace;
mod tests_xor_with_processed_trace;
mod xor_circuit;
mod xor_circuit_autogenerated;

#[derive(Clone)]
pub struct XorConfig<F: PrimeField> {
    _ph: PhantomData<F>,
    xor_chip: XorChip<F>,
    decompose_8_chip: Decompose8Chip<F>,
}
