use super::*;
use crate::auxiliar_functions::value_for;
use crate::tests::tests_xor::xor_circuit_autogenerated::XorCircuitAutogenerated;

#[test]
fn test_positive_xor() {
    let a = (1u128 << 64) - 1;

    test_xor_operation(a, a, a ^ a);
}

#[test]
#[should_panic]
fn test_negative_xor() {
    let a = (1u128 << 64) - 1;
    let b = 0;

    test_xor_operation(a, b, b);
}

fn test_xor_operation(a: u128, b: u128, result: u128) {
    let circuit =
        XorCircuitAutogenerated::<Fr>::new_for(value_for(a), value_for(b), value_for(result));
    let prover = MockProver::run(17, &circuit, vec![]).unwrap();

    prover.verify().unwrap();
}
