use super::*;

use crate::base_operations::decompose_8::Decompose8Config;
use crate::types::{AssignedBlake2bWord, AssignedElement};
use halo2_proofs::circuit::SimpleFloorPlanner;
use halo2_proofs::plonk::{Circuit, Fixed};
use std::array;

pub struct AdditionMod64Circuit8BitsAutogenerated<F: PrimeField> {
    _ph: PhantomData<F>,
    value_a: Value<F>,
    value_b: Value<F>,
    expected_result: Value<F>,
    expected_carry: Value<F>,
}

#[derive(Clone)]
pub struct AdditionMod64Config8BitsWithResultValidation<F: PrimeField> {
    _ph: PhantomData<F>,
    add_config: AdditionMod64Config8Bits<F>,
    fixed_result: Column<Fixed>,
    fixed_carry: Column<Fixed>,
    full_number_u64: Column<Advice>
}

impl<F: PrimeField> Circuit<F> for AdditionMod64Circuit8BitsAutogenerated<F> {
    type Config = AdditionMod64Config8BitsWithResultValidation<F>;
    type FloorPlanner = SimpleFloorPlanner;

    fn without_witnesses(&self) -> Self {
        Self {
            _ph: PhantomData,
            value_a: Value::unknown(),
            value_b: Value::unknown(),
            expected_result: Value::unknown(),
            expected_carry: Value::unknown(),
        }
    }

    #[allow(unused_variables)]
    fn configure(meta: &mut ConstraintSystem<F>) -> Self::Config {
        let full_number_u64 = meta.advice_column();
        let limbs: [Column<Advice>; 8] = array::from_fn(|_| meta.advice_column());

        let decompose_8_config = Decompose8Config::configure(meta, full_number_u64, limbs);
        let addition_config = AdditionMod64Config::configure(meta, full_number_u64, limbs[0]);

        let fixed_result = meta.fixed_column();
        let fixed_carry = meta.fixed_column();
        meta.enable_equality(full_number_u64);
        meta.enable_equality(limbs[0]);
        meta.enable_equality(fixed_result);
        meta.enable_equality(fixed_carry);

        Self::Config {
            _ph: PhantomData,
            add_config: AdditionMod64Config8Bits {
                _ph: PhantomData,
                sum_8bits_config: addition_config,
                decompose_8_config,
            },
            fixed_result,
            fixed_carry,
            full_number_u64
        }
    }

    #[allow(unused_variables)]
    fn synthesize(
        &self,
        config: Self::Config,
        mut layouter: impl Layouter<F>,
    ) -> Result<(), Error> {
        config.add_config.decompose_8_config.populate_lookup_table(&mut layouter)?;
        layouter.assign_region(
            || "sum",
            |mut region| {
                let mut offset = 0;
                let a_cell = config.add_config.decompose_8_config.generate_row_from_value(
                    &mut region,
                    self.value_a,
                    offset,
                )?;
                offset += 1;
                let b_cell = config.add_config.decompose_8_config.generate_row_from_value(
                    &mut region,
                    self.value_b,
                    offset,
                )?;
                offset += 1;

                let result_and_carry =
                    config.add_config.sum_8bits_config.generate_addition_rows_from_cells(
                        &mut region,
                        &mut offset,
                        &AssignedBlake2bWord(a_cell),
                        &AssignedBlake2bWord(b_cell),
                        &config.add_config.decompose_8_config,
                        false,
                        config.full_number_u64,
                    )?;

                Self::assert_cell_value(
                    &mut region,
                    &result_and_carry.0,
                    config.fixed_result,
                    self.expected_result,
                )?;
                Self::assert_cell_value(
                    &mut region,
                    &result_and_carry.1,
                    config.fixed_carry,
                    self.expected_carry,
                )?;
                Ok(())
            },
        )?;
        Ok(())
    }
}

impl<F: PrimeField> AdditionMod64Circuit8BitsAutogenerated<F> {
    fn assert_cell_value(
        region: &mut Region<F>,
        cell: &impl AssignedElement<F>,
        fixed_column: Column<Fixed>,
        expected_value: Value<F>,
    ) -> Result<(), Error> {
        let fixed_cell =
            region.assign_fixed(|| "assign fixed", fixed_column, 0, || expected_value)?;
        region.constrain_equal(cell.cell(), fixed_cell.cell())?;
        Ok(())
    }
}

impl<F: PrimeField> AdditionMod64Circuit8BitsAutogenerated<F> {
    pub fn new_for(
        value_a: Value<F>,
        value_b: Value<F>,
        expected_result: Value<F>,
        expected_carry: Value<F>,
    ) -> Self {
        Self {
            _ph: PhantomData,
            value_a,
            value_b,
            expected_result,
            expected_carry,
        }
    }
}
