use super::*;
use crate::tests::tests_rotation::limb_rotation_circuit::LimbRotationCircuit;
use crate::tests::tests_rotation::rotation_24_ciruit::Rotation24Circuit;
use crate::tests::tests_rotation::rotation_63_circuit_16bit_limbs::Rotation63Circuit16bitLimbs;
use halo2_proofs::circuit::Value;
use halo2_proofs::dev::MockProver;
use halo2_proofs::halo2curves::bn256::Fr;
use rand::Rng;
use crate::chips::decompose_8_chip::Decompose8Chip;
use crate::chips::rotate_63_chip::Rotate63Chip;

#[cfg(test)]
mod test_rotation_63_16_bit_limbs;
mod rotation_63_circuit_16bit_limbs;

// -------- Rotation 63 with 8 bit limbs ------------
#[cfg(test)]
mod test_rotation_63_8_bit_limbs;
mod rotation_63_circuit_8bit_limbs;

#[cfg(test)]
mod test_rotation_63_8_bit_limbs_autogenerated;
mod rotation_63_cirtuit_8bit_limbs_autogenerated;

#[derive(Clone)]
pub struct Rotation63Config8bitLimbs<F: PrimeField> {
    _ph: PhantomData<F>,
    rotation_63_chip: Rotate63Chip<F, 8, 9>,
    decompose_8_chip: Decompose8Chip<F>,
}

// --------------------------------------------------

#[cfg(test)]
mod test_rotation_24_16_bit_limbs;
mod rotation_24_ciruit;

#[cfg(test)]
mod test_limb_rotation_16_24_32;
mod limb_rotation_circuit;
