use crate::tests::tests_rotation::rotation_63_cirtuit_8bit_limbs_autogenerated::Rotation63Circuit8bitLimbsAutogenerated;
use super::*;

#[test]
fn test_rot_63_chip_should_know_how_to_create_trace_from_inputs(){
    let circuit = Rotation63Circuit8bitLimbsAutogenerated::new_for(
        value_for::<u8, Fr>(1u8),
        value_for::<u8, Fr>(2u8)
    );
    let prover = MockProver::run(17, &circuit, vec![]).unwrap();
    assert_eq!(prover.verify(), Ok(()));
}

#[test]
#[should_panic]
fn test_rot_63_chip_should_panic_over_a_wrong_result(){
    let circuit = Rotation63Circuit8bitLimbsAutogenerated::new_for(
        value_for::<u8, Fr>(1u8),
        value_for::<u8, Fr>(3u8)
    );
    let prover = MockProver::run(17, &circuit, vec![]).unwrap();
    assert_eq!(prover.verify(), Ok(()));
}

