use super::*;
use crate::chips::addition_mod_64::{AdditionConfigWith8Limbs};
use crate::chips::decompose_8::Decompose8Config;

mod test_addition_mod_64_with_autogenerated_trace;
mod test_addition_mod_64_with_processed_trace;

mod addition_mod_64_circuit_8bits;
mod addition_mod_64_circuit_8bits_autogenerated;

#[derive(Clone, Debug)]
pub struct AdditionMod64Config8Bits<F: PrimeField + Clone> {
    sum_8bits_config: AdditionConfigWith8Limbs<F>,
    decompose_8_config: Decompose8Config<F>,
    _ph: PhantomData<F>,
}
